# Generated by Django 5.0 on 2023-12-20 18:14

import django.core.validators
import django.db.models.deletion
import recipes_project_app.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.CharField(db_column='ingredients', max_length=500)),
                ('instructions', models.CharField(db_column='instructions', max_length=500)),
                ('level', models.CharField(db_column='level', max_length=10, validators=[recipes_project_app.validators.validator_level])),
                ('delete', models.BooleanField(db_column='delete', default=False)),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, db_column='profession', max_length=256, null=True)),
                ('address', models.CharField(blank=True, db_column='address', max_length=256, null=True)),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.RESTRICT, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_number', models.SmallIntegerField(db_column='rating_number', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_date', models.DateField(auto_now_add=True, db_column='rating_date')),
                ('recipe', models.ForeignKey(db_column='recipe', on_delete=django.db.models.deletion.RESTRICT, related_name='rating', to='recipes_project_app.recipe')),
            ],
            options={
                'db_table': 'rating',
            },
        ),
    ]
